[project]
name = "dl_practice"
version = "0.1.0"
description = "Practicing DL via DUDL course"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy==1.26.4",
    "scipy>=1.16.3",
    "sympy>=1.14.0",
    "torch==2.1.0",
]
